### ISSUE TITLE
meta: tracking use proto submodule

### ISSUE THREAD

**Issue by alissa-tung** [hstreamdb/protocol#6]
- [x] https://github.com/hstreamdb/protocol/pull/5
- [x] #7
- [x] https://github.com/hstreamdb/hstreamdb-java/pull/122
- [ ] https://github.com/hstreamdb/hstreamdb-go/pull/25
- [x] https://github.com/hstreamdb/hstream/pull/966
- [x] https://github.com/hstreamdb/integration-tests/pull/56
